import './globals.css'
import Navigation from '@/Components/Navigation'
import { Open_Sans } from 'next/font/google'

const open_Sans = Open_Sans({
  weight: '300', 
  subsets: ['latin'] 
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={open_Sans.className}>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
